### ISSUE TITLE
Add header files to Project Window

### ISSUE THREAD

**Issue by ghost** [HaikuArchives/Paladin#135] opened 2018-09-27 15:55 UTC
Good day,

When adding a new CPP file to the project, it asks to add a Header file too. If the tick box is marked, the file is created but not added to the project, instead needs to be added manually from the "Add files to project".
This does not make any sense, as I have already told Paladin to create a Header file and add it to the project when I added the CPP file.

Regards,
RR

**Comment by adamfowleruk** [comment] 2018-09-27 20:01
Duplicate of #30

**Closed as completed by adamfowleruk** 2018-09-27 20:01 UTC
Labels: duplicate
