### ISSUE TITLE
haikuporter build is broken

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/Paladin#283] opened 2019-12-16 09:36 UTC
LibWindow.cpp:60:52: error: 'B_SCROLL_VIEW_AWARE' was not declared in this scope

https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/3877/builds/14819.log

**Comment by adamfowleruk** [comment] 2019-12-16 09:46
How bizarre. That line hasn't changed since March when humdinger modified that code for building on beta1. I think this might be a platform specific thing. Let me research the code...

**Comment by adamfowleruk** [comment] 2019-12-16 09:46
B_WILL_DRAW was available in BeOS R3, B_SCROLL_VIEW_AWARE was available in Haiku R1. Log indicates potentially a zeta build??? (Looking at -D flags)... will check.

**Comment by adamfowleruk** [comment] 2019-12-16 17:00
I cannot reproduce your issue, but I did try a completely fresh haiku install and rebuild of paladin using haikuports. It failed. I've resolved that and pushed the changes. Please check if they fix your issue too @diversys

**Comment by diversys** [comment] 2019-12-16 18:39
I can't test it myself but you can update srcGitRev in Paladin recipe and it will trigger rebuild at haikuporter buildmaster.

**Comment by diversys** [comment] 2019-12-17 08:29
New build still fails there https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/3881/builds/14878.log

**Comment by adamfowleruk** [comment] 2019-12-17 11:20
How bizarre... I'm going to add a guard around the flag that humdinger added. That flag is marked as Haiku R1 rather than BeOS R3 like the other flag. Quite why that causes the build to puke I don't know. I'd imagine the build machine is Linux targeting the latest Haiku 64 bit?

**Comment by diversys** [comment] 2019-12-17 11:26
Nope, I think this is actually beta 1 spinning in a VM. See from the log:
/boot/home/haikuports/packages/haiku-r1~beta1_hrev52295_129-1-x86_64.hpkg

**Comment by adamfowleruk** [comment] 2019-12-17 19:57
Ah interesting... Perhaps that is indeed a new flag introduced since Beta 1. @humdingerb mentions something about this in his commit. I'll try and add a guard.

**Closed as completed** 2019-12-17 21:32 UTC
Labels: bug
